### ISSUE TITLE
How to remove inline css?

### ISSUE THREAD

**Issue by cefewow** [dariodev/themelia#3]
this
<style id='themelia-style-inline-css' type='text/css'>

Bump

**Comment by dariodev** [comment]
That inline style is generated by your settings in the Customizer. I'd love to know why you want to remove it.
If you have decided to remove it, try a function like this:
```
add_action( 'wp_print_styles', function() {
    // Remove dynamic inline style
    wp_styles()->add_data( 'themelia-style', 'after', '' );
});
```

**Comment by dariodev** [comment]
Does that work for you? Have you had a chance to try it out?
