### ISSUE TITLE
hide author in Discord OGP preview 

### ISSUE THREAD

**Issue by phantom-z** [dariodev/themelia#4]
Hi dariodev,  

I know you are Pro in Wordpress, i hope you can help me.  When i use open graph protocol meta Discord app displays author name, and I don't want it shown. How can i remove it? 

I even did my minimal theme from scratch, removed author tags everywhere, but it still shows the name... how? O_o

Detailed description of a similar problem
https://stackoverflow.com/questions/43990904/wordpress-discord-preview

**Comment by dariodev** [comment]
As much as I'd love to help I must close this issue as being Themelia unrelated question.
