### ISSUE TITLE
To fix the header on the page with the archive

### ISSUE THREAD

**Issue by getnaked** [dariodev/themelia#5]
In Title between the month and year missing whitespace.
<img width="600" alt="2017-12-20 17-54-23" src="https://user-images.githubusercontent.com/13286033/34203834-0826fa94-e5af-11e7-8ae5-266a2f04794b.png">

**Comment by dariodev** [comment]
It is fixed in latest commit, version 1.2.1 in master branch. I will push changes to wp.org soon. Thank you for reporting!
