### ISSUE TITLE
No tag for released v1.2.2.

### ISSUE THREAD

**Issue by kfogel** [dariodev/themelia#6]
http://relishpress.com/themes/themelia/ says that the latest version is v1.2.2, but there doesn't seem to be any git tag "v1.2.2" in the repository yet.  Just an oversight?

Thanks for Themelia (I installed it on https://rants.org/ yesterday and am still configuring).

**Comment by dariodev** [comment]
Thank you for letting me know! :+1: I just pushed the latest version v1.2.3 and created a tag.
