### ISSUE TITLE
(Noobish question) Inheriting the Customizer in a child theme

### ISSUE THREAD

**Issue by jlbrewer** [dariodev/themelia#8]
Working with a child theme, when I change an appearance setting using the customizer, it displays in the preview but it doesn't take on the live page. This is a single-purpose theme and the settings I'm hard-coding into the child theme are probably going to be the ones that will stick but I'd like to know what's going on for future reference, as customizer support is one of the reasons I picked Themelia as a base for this project - easy prototyping for me, option for the site owner to tweak things later.

The entirety of my functions.php file, more or less pasted from the WP docs:

`<?php
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
 
    $parent_style = 'themelia';
 
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'themelia-child',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}
?>`

**Comment by dariodev** [comment]
Customizer works normally in Themelia child themes. Problem is with the function you are using. You don't need that function. That is the old way of creating child themes. Themelia child theme will automatically enqueue parent theme style. With the function you are using you get the style.css enqueued twice and it is enqueued after customizer styles, so it overrides style generated by customizer.
